[gamevals.tables]
smithing_crystal_singing=1210
smithing_dragon_forge=1211
smithing_cannon_balls=1212
smithing_bars=1213

[gamevals.dbrows]

bow_of_faerdhinen_charged=96742
blade_of_saeldor_charged=96743
bow_of_faerdhinen=96744
blade_of_saeldor=96745
eternal_teleport_crystal=96746
enhanced_crystal_key=96747
crystal_shield=96748
crystal_halberd=96749
crystal_bow=96750
crystal_pickaxe=96751
crystal_harpoon=96752
crystal_felling_axe=96753
crystal_axe=96754
crystal_body=96755
crystal_legs=96756
crystal_helm=96757
crystal_celestial_signet=96758

dragon_keel_parts=96759
dragon_key=96760
dragon_kiteshield=96761
dragon_nails=96762
dragon_platebody=96763
large_dragon_keel_parts=96764

bronze_cannon_ball=96765
iron_cannon_ball=96766
steel_cannon_ball=96767
mithril_cannon_ball=96768
adamantite_cannon_ball=96769
runite_cannon_ball=96770

bronze=96771
blurite=96772
iron=96773
silver=96774
elemental=96775
lead=96776
steel=96777
gold=96778
lovakite=96779
mithril=96780
adamantite=96781
cupronickel=96782
runite=96783