[gamevals.tables]
smithing_dragon_forge=1211
smithing_cannon_balls=1212
smithing_bars=1213

[gamevals.dbrows]
dragon_keel_parts=96759
dragon_key=96760
dragon_kiteshield=96761
dragon_nails=96762
dragon_platebody=96763
large_dragon_keel_parts=96764

bronze_cannon_ball=96765
iron_cannon_ball=96766
steel_cannon_ball=96767
mithril_cannon_ball=96768
adamantite_cannon_ball=96769
runite_cannon_ball=96770

bronze=96771
blurite=96772
iron=96773
silver=96774
elemental=96775
lead=96776
steel=96777
gold=96778
lovakite=96779
mithril=96780
adamantite=96781
cupronickel=96782
runite=96783