[gamevals.tables]
slayer_masters= 65536

[gamevals.dbrows]
turael_aya= 65536
spira= 65537
krystilia= 65538
mazchna_achtryn= 65539
vannaka= 65540
chaeldar= 65541
konar= 65542
nieve_steve= 65543
duradel_kuradal= 65544