[gamevals.tables]
cooking_recipes=1236
cooking_actions=1237
cooking_action_inputs=1238
cooking_action_outcomes=1239

[gamevals.dbrows]
cooking_shrimps=982014
cooking_anchovies=982015
cooking_sardine=982016
cooking_herring=982017
cooking_mackerel=982018
cooking_trout=982019
cooking_salmon=982020
cooking_lobster=982021
cooking_swordfish=982022
cooking_shark=982023
cooking_beef=982024
cooking_chicken=982025

cooking_cod=982026
cooking_pike=982027
cooking_tuna=982028
cooking_bass=982029
cooking_monkfish=982030
cooking_sea_turtle=982031
cooking_anglerfish=982032
cooking_dark_crab=982033
cooking_manta_ray=982034

cooking_karambwan=982127
cooking_rainbow_fish=982137
cooking_cave_eel=982141

cooking_slimy_eel=982145
cooking_rat_meat=982146
cooking_bear_meat=982147
cooking_rabbit=982148
cooking_ugthanki_meat=982149
cooking_roast_bird_meat=982150

cooking_guppy=982169
cooking_cavefish=982170
cooking_roast_beast_meat=982171
cooking_chompy=982172
cooking_tetra=982173
cooking_catfish=982174

cooking_garden_pie_add_tomato=982098
cooking_garden_pie_add_onion=982099
cooking_garden_pie_add_cabbage=982100
cooking_garden_pie_bake=982101

cooking_shrimps_input_0=982035
cooking_anchovies_input_0=982036
cooking_sardine_input_0=982037
cooking_herring_input_0=982038
cooking_mackerel_input_0=982039
cooking_trout_input_0=982040
cooking_salmon_input_0=982041
cooking_lobster_input_0=982042
cooking_swordfish_input_0=982043
cooking_shark_input_0=982044
cooking_beef_input_0=982045
cooking_chicken_input_0=982046
cooking_cod_input_0=982047
cooking_pike_input_0=982048
cooking_tuna_input_0=982049
cooking_bass_input_0=982050
cooking_monkfish_input_0=982051
cooking_sea_turtle_input_0=982052
cooking_anglerfish_input_0=982053
cooking_dark_crab_input_0=982054
cooking_manta_ray_input_0=982055

cooking_karambwan_input_0=982130
cooking_rainbow_fish_input_0=982138
cooking_cave_eel_input_0=982142

cooking_slimy_eel_input_0=982151
cooking_rat_meat_input_0=982152
cooking_bear_meat_input_0=982153
cooking_rabbit_input_0=982154
cooking_ugthanki_meat_input_0=982155
cooking_roast_bird_meat_input_0=982156

cooking_guppy_input_0=982175
cooking_cavefish_input_0=982176
cooking_roast_beast_meat_input_0=982177
cooking_chompy_input_0=982178
cooking_tetra_input_0=982179
cooking_catfish_input_0=982180

cooking_garden_pie_add_tomato_input_0=982102
cooking_garden_pie_add_tomato_input_1=982103
cooking_garden_pie_add_onion_input_0=982104
cooking_garden_pie_add_onion_input_1=982105
cooking_garden_pie_add_cabbage_input_0=982106
cooking_garden_pie_add_cabbage_input_1=982107
cooking_garden_pie_bake_input_0=982108

cooking_shrimps_outcome_success=982056
cooking_anchovies_outcome_success=982057
cooking_sardine_outcome_success=982058
cooking_herring_outcome_success=982059
cooking_mackerel_outcome_success=982060
cooking_trout_outcome_success=982061
cooking_salmon_outcome_success=982062
cooking_lobster_outcome_success=982063
cooking_swordfish_outcome_success=982064
cooking_shark_outcome_success=982065
cooking_beef_outcome_success=982066
cooking_chicken_outcome_success=982067
cooking_cod_outcome_success=982068
cooking_pike_outcome_success=982069
cooking_tuna_outcome_success=982070
cooking_bass_outcome_success=982071
cooking_monkfish_outcome_success=982072
cooking_sea_turtle_outcome_success=982073
cooking_anglerfish_outcome_success=982074
cooking_dark_crab_outcome_success=982075
cooking_manta_ray_outcome_success=982076

cooking_karambwan_outcome_success=982133
cooking_rainbow_fish_outcome_success=982139
cooking_cave_eel_outcome_success=982143

cooking_slimy_eel_outcome_success=982157
cooking_rat_meat_outcome_success=982158
cooking_bear_meat_outcome_success=982159
cooking_rabbit_outcome_success=982160
cooking_ugthanki_meat_outcome_success=982161
cooking_roast_bird_meat_outcome_success=982162

cooking_guppy_outcome_success=982181
cooking_cavefish_outcome_success=982182
cooking_roast_beast_meat_outcome_success=982183
cooking_chompy_outcome_success=982184
cooking_tetra_outcome_success=982185
cooking_catfish_outcome_success=982186

cooking_garden_pie_add_tomato_outcome_success=982109
cooking_garden_pie_add_onion_outcome_success=982110
cooking_garden_pie_add_cabbage_outcome_success=982111
cooking_garden_pie_bake_outcome_success=982112

cooking_shrimps_outcome_fail=982077
cooking_anchovies_outcome_fail=982078
cooking_sardine_outcome_fail=982079
cooking_herring_outcome_fail=982080
cooking_mackerel_outcome_fail=982081
cooking_trout_outcome_fail=982082
cooking_salmon_outcome_fail=982083
cooking_lobster_outcome_fail=982084
cooking_swordfish_outcome_fail=982085
cooking_shark_outcome_fail=982086
cooking_beef_outcome_fail=982087
cooking_chicken_outcome_fail=982088
cooking_cod_outcome_fail=982089
cooking_pike_outcome_fail=982090
cooking_tuna_outcome_fail=982091
cooking_bass_outcome_fail=982092
cooking_monkfish_outcome_fail=982093
cooking_sea_turtle_outcome_fail=982094
cooking_anglerfish_outcome_fail=982095
cooking_dark_crab_outcome_fail=982096
cooking_manta_ray_outcome_fail=982097

cooking_karambwan_outcome_fail=982136
cooking_rainbow_fish_outcome_fail=982140
cooking_cave_eel_outcome_fail=982144

cooking_slimy_eel_outcome_fail=982163
cooking_rat_meat_outcome_fail=982164
cooking_bear_meat_outcome_fail=982165
cooking_rabbit_outcome_fail=982166
cooking_ugthanki_meat_outcome_fail=982167
cooking_roast_bird_meat_outcome_fail=982168

cooking_guppy_outcome_fail=982187
cooking_cavefish_outcome_fail=982188
cooking_roast_beast_meat_outcome_fail=982189
cooking_chompy_outcome_fail=982190
cooking_tetra_outcome_fail=982191
cooking_catfish_outcome_fail=982192

cooking_garden_pie_bake_outcome_fail=982113

cooking_cake_mix=982114
cooking_cake_bake=982115

cooking_cake_mix_input_0=982116
cooking_cake_mix_input_1=982117
cooking_cake_mix_input_2=982118
cooking_cake_mix_input_3=982119
cooking_cake_bake_input_0=982120

cooking_cake_mix_outcome_success=982121
cooking_cake_bake_outcome_success=982122

cooking_cake_bake_outcome_fail=982123

cooking_cake_mix_outcome_always_0=982124
cooking_cake_mix_outcome_always_1=982125
cooking_cake_bake_outcome_always_0=982126

# --- Skewer (spit-roast prep) entries ---
cooking_skewer_bird_meat=-1
cooking_skewer_beast_meat=-1
cooking_skewer_bird_meat_input_0=-1
cooking_skewer_bird_meat_input_1=-1
cooking_skewer_beast_meat_input_0=-1
cooking_skewer_beast_meat_input_1=-1
cooking_skewer_bird_meat_outcome_success=-1
cooking_skewer_beast_meat_outcome_success=-1

# --- Bread ---
cooking_bread=-1
cooking_pitta_bread=-1

cooking_bread_input_0=-1
cooking_pitta_bread_input_0=-1

cooking_bread_outcome_success=-1
cooking_bread_outcome_fail=-1
cooking_pitta_bread_outcome_success=-1
cooking_pitta_bread_outcome_fail=-1

# --- Pies ---
cooking_redberry_pie_add_berries=-1
cooking_redberry_pie_bake=-1
cooking_redberry_pie_add_berries_input_0=-1
cooking_redberry_pie_add_berries_input_1=-1
cooking_redberry_pie_bake_input_0=-1
cooking_redberry_pie_add_berries_outcome_success=-1
cooking_redberry_pie_bake_outcome_success=-1
cooking_redberry_pie_bake_outcome_fail=-1

cooking_meat_pie_add_meat=-1
cooking_meat_pie_bake=-1
cooking_meat_pie_add_meat_input_0=-1
cooking_meat_pie_add_meat_input_1=-1
cooking_meat_pie_bake_input_0=-1
cooking_meat_pie_add_meat_outcome_success=-1
cooking_meat_pie_bake_outcome_success=-1
cooking_meat_pie_bake_outcome_fail=-1

cooking_mud_pie_add_compost=-1
cooking_mud_pie_add_water=-1
cooking_mud_pie_add_clay=-1
cooking_mud_pie_bake=-1
cooking_mud_pie_add_compost_input_0=-1
cooking_mud_pie_add_compost_input_1=-1
cooking_mud_pie_add_water_input_0=-1
cooking_mud_pie_add_water_input_1=-1
cooking_mud_pie_add_clay_input_0=-1
cooking_mud_pie_add_clay_input_1=-1
cooking_mud_pie_bake_input_0=-1
cooking_mud_pie_add_compost_outcome_success=-1
cooking_mud_pie_add_water_outcome_success=-1
cooking_mud_pie_add_water_outcome_always_0=-1
cooking_mud_pie_add_clay_outcome_success=-1
cooking_mud_pie_bake_outcome_success=-1
cooking_mud_pie_bake_outcome_fail=-1

cooking_apple_pie_add_apple=-1
cooking_apple_pie_bake=-1
cooking_apple_pie_add_apple_input_0=-1
cooking_apple_pie_add_apple_input_1=-1
cooking_apple_pie_bake_input_0=-1
cooking_apple_pie_add_apple_outcome_success=-1
cooking_apple_pie_bake_outcome_success=-1
cooking_apple_pie_bake_outcome_fail=-1

cooking_fish_pie_add_trout=-1
cooking_fish_pie_add_cod=-1
cooking_fish_pie_add_potato=-1
cooking_fish_pie_bake=-1
cooking_fish_pie_add_trout_input_0=-1
cooking_fish_pie_add_trout_input_1=-1
cooking_fish_pie_add_cod_input_0=-1
cooking_fish_pie_add_cod_input_1=-1
cooking_fish_pie_add_potato_input_0=-1
cooking_fish_pie_add_potato_input_1=-1
cooking_fish_pie_bake_input_0=-1
cooking_fish_pie_add_trout_outcome_success=-1
cooking_fish_pie_add_cod_outcome_success=-1
cooking_fish_pie_add_potato_outcome_success=-1
cooking_fish_pie_bake_outcome_success=-1
cooking_fish_pie_bake_outcome_fail=-1

cooking_botanical_pie_add_golovanova=-1
cooking_botanical_pie_bake=-1
cooking_botanical_pie_add_golovanova_input_0=-1
cooking_botanical_pie_add_golovanova_input_1=-1
cooking_botanical_pie_bake_input_0=-1
cooking_botanical_pie_add_golovanova_outcome_success=-1
cooking_botanical_pie_bake_outcome_success=-1
cooking_botanical_pie_bake_outcome_fail=-1

cooking_mushroom_pie_add_sulliuscep=-1
cooking_mushroom_pie_bake=-1
cooking_mushroom_pie_add_sulliuscep_input_0=-1
cooking_mushroom_pie_add_sulliuscep_input_1=-1
cooking_mushroom_pie_bake_input_0=-1
cooking_mushroom_pie_add_sulliuscep_outcome_success=-1
cooking_mushroom_pie_bake_outcome_success=-1
cooking_mushroom_pie_bake_outcome_fail=-1

cooking_admiral_pie_add_salmon=-1
cooking_admiral_pie_add_tuna=-1
cooking_admiral_pie_add_potato=-1
cooking_admiral_pie_bake=-1
cooking_admiral_pie_add_salmon_input_0=-1
cooking_admiral_pie_add_salmon_input_1=-1
cooking_admiral_pie_add_tuna_input_0=-1
cooking_admiral_pie_add_tuna_input_1=-1
cooking_admiral_pie_add_potato_input_0=-1
cooking_admiral_pie_add_potato_input_1=-1
cooking_admiral_pie_bake_input_0=-1
cooking_admiral_pie_add_salmon_outcome_success=-1
cooking_admiral_pie_add_tuna_outcome_success=-1
cooking_admiral_pie_add_potato_outcome_success=-1
cooking_admiral_pie_bake_outcome_success=-1
cooking_admiral_pie_bake_outcome_fail=-1

cooking_dragonfruit_pie_add_fruit=-1
cooking_dragonfruit_pie_bake=-1
cooking_dragonfruit_pie_add_fruit_input_0=-1
cooking_dragonfruit_pie_add_fruit_input_1=-1
cooking_dragonfruit_pie_bake_input_0=-1
cooking_dragonfruit_pie_add_fruit_outcome_success=-1
cooking_dragonfruit_pie_bake_outcome_success=-1
cooking_dragonfruit_pie_bake_outcome_fail=-1

cooking_wild_pie_add_bear=-1
cooking_wild_pie_add_chompy=-1
cooking_wild_pie_add_rabbit=-1
cooking_wild_pie_bake=-1
cooking_wild_pie_add_bear_input_0=-1
cooking_wild_pie_add_bear_input_1=-1
cooking_wild_pie_add_chompy_input_0=-1
cooking_wild_pie_add_chompy_input_1=-1
cooking_wild_pie_add_rabbit_input_0=-1
cooking_wild_pie_add_rabbit_input_1=-1
cooking_wild_pie_bake_input_0=-1
cooking_wild_pie_add_bear_outcome_success=-1
cooking_wild_pie_add_chompy_outcome_success=-1
cooking_wild_pie_add_rabbit_outcome_success=-1
cooking_wild_pie_bake_outcome_success=-1
cooking_wild_pie_bake_outcome_fail=-1

cooking_summer_pie_add_watermelon=-1
cooking_summer_pie_add_apple=-1
cooking_summer_pie_add_strawberry=-1
cooking_summer_pie_bake=-1
cooking_summer_pie_add_watermelon_input_0=-1
cooking_summer_pie_add_watermelon_input_1=-1
cooking_summer_pie_add_apple_input_0=-1
cooking_summer_pie_add_apple_input_1=-1
cooking_summer_pie_add_strawberry_input_0=-1
cooking_summer_pie_add_strawberry_input_1=-1
cooking_summer_pie_bake_input_0=-1
cooking_summer_pie_add_watermelon_outcome_success=-1
cooking_summer_pie_add_apple_outcome_success=-1
cooking_summer_pie_add_strawberry_outcome_success=-1
cooking_summer_pie_bake_outcome_success=-1
cooking_summer_pie_bake_outcome_fail=-1

# --- Pizzas ---
cooking_pizza_add_tomato=-1
cooking_pizza_add_cheese=-1
cooking_pizza_bake=-1
cooking_pizza_add_tomato_input_0=-1
cooking_pizza_add_tomato_input_1=-1
cooking_pizza_add_cheese_input_0=-1
cooking_pizza_add_cheese_input_1=-1
cooking_pizza_bake_input_0=-1
cooking_pizza_add_tomato_outcome_success=-1
cooking_pizza_add_cheese_outcome_success=-1
cooking_pizza_bake_outcome_success=-1
cooking_pizza_bake_outcome_fail=-1

cooking_pizza_add_meat=-1
cooking_pizza_add_meat_input_0=-1
cooking_pizza_add_meat_input_1=-1
cooking_pizza_add_meat_outcome_success=-1

cooking_pizza_add_anchovies=-1
cooking_pizza_add_anchovies_input_0=-1
cooking_pizza_add_anchovies_input_1=-1
cooking_pizza_add_anchovies_outcome_success=-1

cooking_pizza_add_pineapple=-1
cooking_pizza_add_pineapple_input_0=-1
cooking_pizza_add_pineapple_input_1=-1
cooking_pizza_add_pineapple_outcome_success=-1

# --- Stews ---
cooking_stew_add_potato=-1
cooking_stew_add_meat=-1
cooking_stew_cook=-1
cooking_stew_add_potato_input_0=-1
cooking_stew_add_potato_input_1=-1
cooking_stew_add_meat_input_0=-1
cooking_stew_add_meat_input_1=-1
cooking_stew_cook_input_0=-1
cooking_stew_add_potato_outcome_success=-1
cooking_stew_add_meat_outcome_success=-1
cooking_stew_cook_outcome_success=-1
cooking_stew_cook_outcome_fail=-1

cooking_curry_add_potato=-1
cooking_curry_add_meat=-1
cooking_curry_add_spice=-1
cooking_curry_cook=-1
cooking_curry_add_potato_input_0=-1
cooking_curry_add_potato_input_1=-1
cooking_curry_add_meat_input_0=-1
cooking_curry_add_meat_input_1=-1
cooking_curry_add_spice_input_0=-1
cooking_curry_add_spice_input_1=-1
cooking_curry_cook_input_0=-1
cooking_curry_add_potato_outcome_success=-1
cooking_curry_add_meat_outcome_success=-1
cooking_curry_add_spice_outcome_success=-1
cooking_curry_cook_outcome_success=-1
cooking_curry_cook_outcome_fail=-1

# --- Potatoes ---
cooking_baked_potato=-1
cooking_baked_potato_input_0=-1
cooking_baked_potato_outcome_success=-1
cooking_baked_potato_outcome_fail=-1

cooking_potato_add_butter=-1
cooking_potato_add_butter_input_0=-1
cooking_potato_add_butter_input_1=-1
cooking_potato_add_butter_outcome_success=-1

cooking_potato_add_cheese=-1
cooking_potato_add_cheese_input_0=-1
cooking_potato_add_cheese_input_1=-1
cooking_potato_add_cheese_outcome_success=-1

cooking_potato_add_egg=-1
cooking_potato_add_egg_input_0=-1
cooking_potato_add_egg_input_1=-1
cooking_potato_add_egg_outcome_success=-1
cooking_potato_add_egg_outcome_always_0=-1

cooking_potato_add_mushroom_onion=-1
cooking_potato_add_mushroom_onion_input_0=-1
cooking_potato_add_mushroom_onion_input_1=-1
cooking_potato_add_mushroom_onion_outcome_success=-1
cooking_potato_add_mushroom_onion_outcome_always_0=-1

cooking_potato_add_tuna_corn=-1
cooking_potato_add_tuna_corn_input_0=-1
cooking_potato_add_tuna_corn_input_1=-1
cooking_potato_add_tuna_corn_outcome_success=-1
cooking_potato_add_tuna_corn_outcome_always_0=-1

# --- Misc foods ---
cooking_sweetcorn=-1
cooking_sweetcorn_input_0=-1
cooking_sweetcorn_outcome_success=-1
cooking_sweetcorn_outcome_fail=-1

cooking_scrambled_egg_mix=-1
cooking_scrambled_egg_cook=-1
cooking_scrambled_egg_mix_input_0=-1
cooking_scrambled_egg_mix_input_1=-1
cooking_scrambled_egg_cook_input_0=-1
cooking_scrambled_egg_mix_outcome_success=-1
cooking_scrambled_egg_cook_outcome_success=-1
cooking_scrambled_egg_cook_outcome_fail=-1

cooking_fried_onions=-1
cooking_fried_onions_input_0=-1
cooking_fried_onions_outcome_success=-1
cooking_fried_onions_outcome_fail=-1

cooking_fried_mushrooms=-1
cooking_fried_mushrooms_input_0=-1
cooking_fried_mushrooms_outcome_success=-1
cooking_fried_mushrooms_outcome_fail=-1

cooking_mushroom_onion_combine=-1
cooking_mushroom_onion_combine_input_0=-1
cooking_mushroom_onion_combine_input_1=-1
cooking_mushroom_onion_combine_outcome_success=-1
cooking_mushroom_onion_combine_outcome_always_0=-1

cooking_tuna_corn_combine=-1
cooking_tuna_corn_combine_input_0=-1
cooking_tuna_corn_combine_input_1=-1
cooking_tuna_corn_combine_input_2=-1
cooking_tuna_corn_combine_outcome_success=-1

cooking_chocolate_cake=-1
cooking_chocolate_cake_input_0=-1
cooking_chocolate_cake_input_1=-1
cooking_chocolate_cake_outcome_success=-1

# --- Wine ---
cooking_wine=-1
cooking_wine_input_0=-1
cooking_wine_input_1=-1
cooking_wine_outcome_success=-1
cooking_wine_outcome_fail=-1

# --- Snails ---
cooking_thin_snail=-1
cooking_thin_snail_input_0=-1
cooking_thin_snail_outcome_success=-1
cooking_thin_snail_outcome_fail=-1

cooking_lean_snail=-1
cooking_lean_snail_input_0=-1
cooking_lean_snail_outcome_success=-1
cooking_lean_snail_outcome_fail=-1

cooking_fat_snail=-1
cooking_fat_snail_input_0=-1
cooking_fat_snail_outcome_success=-1
cooking_fat_snail_outcome_fail=-1

# --- Spit-Roast Rabbit ---
cooking_skewer_rabbit_meat=-1
cooking_skewer_rabbit_meat_input_0=-1
cooking_skewer_rabbit_meat_input_1=-1
cooking_skewer_rabbit_meat_outcome_success=-1

cooking_roast_rabbit_meat=-1
cooking_roast_rabbit_meat_input_0=-1
cooking_roast_rabbit_meat_outcome_success=-1
cooking_roast_rabbit_meat_outcome_fail=-1

# --- Hunter Meats (Pitfall Trapping) ---
cooking_larupia=-1
cooking_larupia_input_0=-1
cooking_larupia_outcome_success=-1
cooking_larupia_outcome_fail=-1

cooking_graahk=-1
cooking_graahk_input_0=-1
cooking_graahk_outcome_success=-1
cooking_graahk_outcome_fail=-1

cooking_kyatt=-1
cooking_kyatt_input_0=-1
cooking_kyatt_outcome_success=-1
cooking_kyatt_outcome_fail=-1

cooking_pyre_fox=-1
cooking_pyre_fox_input_0=-1
cooking_pyre_fox_outcome_success=-1
cooking_pyre_fox_outcome_fail=-1

cooking_sunlight_antelope=-1
cooking_sunlight_antelope_input_0=-1
cooking_sunlight_antelope_outcome_success=-1
cooking_sunlight_antelope_outcome_fail=-1

cooking_moonlight_antelope=-1
cooking_moonlight_antelope_input_0=-1
cooking_moonlight_antelope_outcome_success=-1
cooking_moonlight_antelope_outcome_fail=-1
