[gamevals.tables]
cooking_recipes=1236
cooking_actions=1237
cooking_action_inputs=1238
cooking_action_outcomes=1239

[gamevals.dbrows]
cooking_shrimps=982014
cooking_anchovies=982015
cooking_sardine=982016
cooking_herring=982017
cooking_mackerel=982018
cooking_trout=982019
cooking_salmon=982020
cooking_lobster=982021
cooking_swordfish=982022
cooking_shark=982023
cooking_beef=982024
cooking_chicken=982025

cooking_cod=982026
cooking_pike=982027
cooking_tuna=982028
cooking_bass=982029
cooking_monkfish=982030
cooking_sea_turtle=982031
cooking_anglerfish=982032
cooking_dark_crab=982033
cooking_manta_ray=982034

cooking_karambwan=982127
cooking_rainbow_fish=982137
cooking_cave_eel=982141

cooking_slimy_eel=982145
cooking_rat_meat=982146
cooking_bear_meat=982147
cooking_rabbit=982148
cooking_ugthanki_meat=982149
cooking_roast_bird_meat=982150

cooking_guppy=982169
cooking_cavefish=982170
cooking_roast_beast_meat=982171
cooking_chompy=982172
cooking_tetra=982173
cooking_catfish=982174

cooking_garden_pie_add_tomato=982098
cooking_garden_pie_add_onion=982099
cooking_garden_pie_add_cabbage=982100
cooking_garden_pie_bake=982101

cooking_shrimps_input_0=982035
cooking_anchovies_input_0=982036
cooking_sardine_input_0=982037
cooking_herring_input_0=982038
cooking_mackerel_input_0=982039
cooking_trout_input_0=982040
cooking_salmon_input_0=982041
cooking_lobster_input_0=982042
cooking_swordfish_input_0=982043
cooking_shark_input_0=982044
cooking_beef_input_0=982045
cooking_chicken_input_0=982046
cooking_cod_input_0=982047
cooking_pike_input_0=982048
cooking_tuna_input_0=982049
cooking_bass_input_0=982050
cooking_monkfish_input_0=982051
cooking_sea_turtle_input_0=982052
cooking_anglerfish_input_0=982053
cooking_dark_crab_input_0=982054
cooking_manta_ray_input_0=982055

cooking_karambwan_input_0=982130
cooking_rainbow_fish_input_0=982138
cooking_cave_eel_input_0=982142

cooking_slimy_eel_input_0=982151
cooking_rat_meat_input_0=982152
cooking_bear_meat_input_0=982153
cooking_rabbit_input_0=982154
cooking_ugthanki_meat_input_0=982155
cooking_roast_bird_meat_input_0=982156

cooking_guppy_input_0=982175
cooking_cavefish_input_0=982176
cooking_roast_beast_meat_input_0=982177
cooking_chompy_input_0=982178
cooking_tetra_input_0=982179
cooking_catfish_input_0=982180

cooking_garden_pie_add_tomato_input_0=982102
cooking_garden_pie_add_tomato_input_1=982103
cooking_garden_pie_add_onion_input_0=982104
cooking_garden_pie_add_onion_input_1=982105
cooking_garden_pie_add_cabbage_input_0=982106
cooking_garden_pie_add_cabbage_input_1=982107
cooking_garden_pie_bake_input_0=982108

cooking_shrimps_outcome_success=982056
cooking_anchovies_outcome_success=982057
cooking_sardine_outcome_success=982058
cooking_herring_outcome_success=982059
cooking_mackerel_outcome_success=982060
cooking_trout_outcome_success=982061
cooking_salmon_outcome_success=982062
cooking_lobster_outcome_success=982063
cooking_swordfish_outcome_success=982064
cooking_shark_outcome_success=982065
cooking_beef_outcome_success=982066
cooking_chicken_outcome_success=982067
cooking_cod_outcome_success=982068
cooking_pike_outcome_success=982069
cooking_tuna_outcome_success=982070
cooking_bass_outcome_success=982071
cooking_monkfish_outcome_success=982072
cooking_sea_turtle_outcome_success=982073
cooking_anglerfish_outcome_success=982074
cooking_dark_crab_outcome_success=982075
cooking_manta_ray_outcome_success=982076

cooking_karambwan_outcome_success=982133
cooking_rainbow_fish_outcome_success=982139
cooking_cave_eel_outcome_success=982143

cooking_slimy_eel_outcome_success=982157
cooking_rat_meat_outcome_success=982158
cooking_bear_meat_outcome_success=982159
cooking_rabbit_outcome_success=982160
cooking_ugthanki_meat_outcome_success=982161
cooking_roast_bird_meat_outcome_success=982162

cooking_guppy_outcome_success=982181
cooking_cavefish_outcome_success=982182
cooking_roast_beast_meat_outcome_success=982183
cooking_chompy_outcome_success=982184
cooking_tetra_outcome_success=982185
cooking_catfish_outcome_success=982186

cooking_garden_pie_add_tomato_outcome_success=982109
cooking_garden_pie_add_onion_outcome_success=982110
cooking_garden_pie_add_cabbage_outcome_success=982111
cooking_garden_pie_bake_outcome_success=982112

cooking_shrimps_outcome_fail=982077
cooking_anchovies_outcome_fail=982078
cooking_sardine_outcome_fail=982079
cooking_herring_outcome_fail=982080
cooking_mackerel_outcome_fail=982081
cooking_trout_outcome_fail=982082
cooking_salmon_outcome_fail=982083
cooking_lobster_outcome_fail=982084
cooking_swordfish_outcome_fail=982085
cooking_shark_outcome_fail=982086
cooking_beef_outcome_fail=982087
cooking_chicken_outcome_fail=982088
cooking_cod_outcome_fail=982089
cooking_pike_outcome_fail=982090
cooking_tuna_outcome_fail=982091
cooking_bass_outcome_fail=982092
cooking_monkfish_outcome_fail=982093
cooking_sea_turtle_outcome_fail=982094
cooking_anglerfish_outcome_fail=982095
cooking_dark_crab_outcome_fail=982096
cooking_manta_ray_outcome_fail=982097

cooking_karambwan_outcome_fail=982136
cooking_rainbow_fish_outcome_fail=982140
cooking_cave_eel_outcome_fail=982144

cooking_slimy_eel_outcome_fail=982163
cooking_rat_meat_outcome_fail=982164
cooking_bear_meat_outcome_fail=982165
cooking_rabbit_outcome_fail=982166
cooking_ugthanki_meat_outcome_fail=982167
cooking_roast_bird_meat_outcome_fail=982168

cooking_guppy_outcome_fail=982187
cooking_cavefish_outcome_fail=982188
cooking_roast_beast_meat_outcome_fail=982189
cooking_chompy_outcome_fail=982190
cooking_tetra_outcome_fail=982191
cooking_catfish_outcome_fail=982192

cooking_garden_pie_bake_outcome_fail=982113

cooking_cake_mix=982114
cooking_cake_bake=982115

cooking_cake_mix_input_0=982116
cooking_cake_mix_input_1=982117
cooking_cake_mix_input_2=982118
cooking_cake_mix_input_3=982119
cooking_cake_bake_input_0=982120

cooking_cake_mix_outcome_success=982121
cooking_cake_bake_outcome_success=982122

cooking_cake_bake_outcome_fail=982123

cooking_cake_mix_outcome_always_0=982124
cooking_cake_mix_outcome_always_1=982125
cooking_cake_bake_outcome_always_0=982126

# --- Skewer (spit-roast prep) entries ---
cooking_skewer_bird_meat=982193
cooking_skewer_beast_meat=982194
cooking_skewer_bird_meat_input_0=982195
cooking_skewer_bird_meat_input_1=982196
cooking_skewer_beast_meat_input_0=982197
cooking_skewer_beast_meat_input_1=982198
cooking_skewer_bird_meat_outcome_success=982199
cooking_skewer_beast_meat_outcome_success=982200

# --- Bread ---
cooking_bread=982201
cooking_pitta_bread=982202

cooking_bread_input_0=982203
cooking_pitta_bread_input_0=982204

cooking_bread_outcome_success=982205
cooking_bread_outcome_fail=982206
cooking_pitta_bread_outcome_success=982207
cooking_pitta_bread_outcome_fail=982208

# --- Pies ---
cooking_redberry_pie_add_berries=982209
cooking_redberry_pie_bake=982210
cooking_redberry_pie_add_berries_input_0=982211
cooking_redberry_pie_add_berries_input_1=982212
cooking_redberry_pie_bake_input_0=982213
cooking_redberry_pie_add_berries_outcome_success=982214
cooking_redberry_pie_bake_outcome_success=982215
cooking_redberry_pie_bake_outcome_fail=982216

cooking_meat_pie_add_meat=982217
cooking_meat_pie_bake=982218
cooking_meat_pie_add_meat_input_0=982219
cooking_meat_pie_add_meat_input_1=982220
cooking_meat_pie_bake_input_0=982221
cooking_meat_pie_add_meat_outcome_success=982222
cooking_meat_pie_bake_outcome_success=982223
cooking_meat_pie_bake_outcome_fail=982224

cooking_mud_pie_add_compost=982225
cooking_mud_pie_add_water=982226
cooking_mud_pie_add_clay=982227
cooking_mud_pie_bake=982228
cooking_mud_pie_add_compost_input_0=982229
cooking_mud_pie_add_compost_input_1=982230
cooking_mud_pie_add_water_input_0=982231
cooking_mud_pie_add_water_input_1=982232
cooking_mud_pie_add_clay_input_0=982233
cooking_mud_pie_add_clay_input_1=982234
cooking_mud_pie_bake_input_0=982235
cooking_mud_pie_add_compost_outcome_success=982236
cooking_mud_pie_add_water_outcome_success=982237
cooking_mud_pie_add_water_outcome_always_0=982238
cooking_mud_pie_add_clay_outcome_success=982239
cooking_mud_pie_bake_outcome_success=982240
cooking_mud_pie_bake_outcome_fail=982241

cooking_apple_pie_add_apple=982242
cooking_apple_pie_bake=982243
cooking_apple_pie_add_apple_input_0=982244
cooking_apple_pie_add_apple_input_1=982245
cooking_apple_pie_bake_input_0=982246
cooking_apple_pie_add_apple_outcome_success=982247
cooking_apple_pie_bake_outcome_success=982248
cooking_apple_pie_bake_outcome_fail=982249

cooking_fish_pie_add_trout=982250
cooking_fish_pie_add_cod=982251
cooking_fish_pie_add_potato=982252
cooking_fish_pie_bake=982253
cooking_fish_pie_add_trout_input_0=982254
cooking_fish_pie_add_trout_input_1=982255
cooking_fish_pie_add_cod_input_0=982256
cooking_fish_pie_add_cod_input_1=982257
cooking_fish_pie_add_potato_input_0=982258
cooking_fish_pie_add_potato_input_1=982259
cooking_fish_pie_bake_input_0=982260
cooking_fish_pie_add_trout_outcome_success=982261
cooking_fish_pie_add_cod_outcome_success=982262
cooking_fish_pie_add_potato_outcome_success=982263
cooking_fish_pie_bake_outcome_success=982264
cooking_fish_pie_bake_outcome_fail=982265

cooking_botanical_pie_add_golovanova=982266
cooking_botanical_pie_bake=982267
cooking_botanical_pie_add_golovanova_input_0=982268
cooking_botanical_pie_add_golovanova_input_1=982269
cooking_botanical_pie_bake_input_0=982270
cooking_botanical_pie_add_golovanova_outcome_success=982271
cooking_botanical_pie_bake_outcome_success=982272
cooking_botanical_pie_bake_outcome_fail=982273

cooking_mushroom_pie_add_sulliuscep=982274
cooking_mushroom_pie_bake=982275
cooking_mushroom_pie_add_sulliuscep_input_0=982276
cooking_mushroom_pie_add_sulliuscep_input_1=982277
cooking_mushroom_pie_bake_input_0=982278
cooking_mushroom_pie_add_sulliuscep_outcome_success=982279
cooking_mushroom_pie_bake_outcome_success=982280
cooking_mushroom_pie_bake_outcome_fail=982281

cooking_admiral_pie_add_salmon=982282
cooking_admiral_pie_add_tuna=982283
cooking_admiral_pie_add_potato=982284
cooking_admiral_pie_bake=982285
cooking_admiral_pie_add_salmon_input_0=982286
cooking_admiral_pie_add_salmon_input_1=982287
cooking_admiral_pie_add_tuna_input_0=982288
cooking_admiral_pie_add_tuna_input_1=982289
cooking_admiral_pie_add_potato_input_0=982290
cooking_admiral_pie_add_potato_input_1=982291
cooking_admiral_pie_bake_input_0=982292
cooking_admiral_pie_add_salmon_outcome_success=982293
cooking_admiral_pie_add_tuna_outcome_success=982294
cooking_admiral_pie_add_potato_outcome_success=982295
cooking_admiral_pie_bake_outcome_success=982296
cooking_admiral_pie_bake_outcome_fail=982297

cooking_dragonfruit_pie_add_fruit=982298
cooking_dragonfruit_pie_bake=982299
cooking_dragonfruit_pie_add_fruit_input_0=982300
cooking_dragonfruit_pie_add_fruit_input_1=982301
cooking_dragonfruit_pie_bake_input_0=982302
cooking_dragonfruit_pie_add_fruit_outcome_success=982303
cooking_dragonfruit_pie_bake_outcome_success=982304
cooking_dragonfruit_pie_bake_outcome_fail=982305

cooking_wild_pie_add_bear=982306
cooking_wild_pie_add_chompy=982307
cooking_wild_pie_add_rabbit=982308
cooking_wild_pie_bake=982309
cooking_wild_pie_add_bear_input_0=982310
cooking_wild_pie_add_bear_input_1=982311
cooking_wild_pie_add_chompy_input_0=982312
cooking_wild_pie_add_chompy_input_1=982313
cooking_wild_pie_add_rabbit_input_0=982314
cooking_wild_pie_add_rabbit_input_1=982315
cooking_wild_pie_bake_input_0=982316
cooking_wild_pie_add_bear_outcome_success=982317
cooking_wild_pie_add_chompy_outcome_success=982318
cooking_wild_pie_add_rabbit_outcome_success=982319
cooking_wild_pie_bake_outcome_success=982320
cooking_wild_pie_bake_outcome_fail=982321

cooking_summer_pie_add_watermelon=982322
cooking_summer_pie_add_apple=982323
cooking_summer_pie_add_strawberry=982324
cooking_summer_pie_bake=982325
cooking_summer_pie_add_watermelon_input_0=982326
cooking_summer_pie_add_watermelon_input_1=982327
cooking_summer_pie_add_apple_input_0=982328
cooking_summer_pie_add_apple_input_1=982329
cooking_summer_pie_add_strawberry_input_0=982330
cooking_summer_pie_add_strawberry_input_1=982331
cooking_summer_pie_bake_input_0=982332
cooking_summer_pie_add_watermelon_outcome_success=982333
cooking_summer_pie_add_apple_outcome_success=982334
cooking_summer_pie_add_strawberry_outcome_success=982335
cooking_summer_pie_bake_outcome_success=982336
cooking_summer_pie_bake_outcome_fail=982337

# --- Pizzas ---
cooking_pizza_add_tomato=982338
cooking_pizza_add_cheese=982339
cooking_pizza_bake=982340
cooking_pizza_add_tomato_input_0=982341
cooking_pizza_add_tomato_input_1=982342
cooking_pizza_add_cheese_input_0=982343
cooking_pizza_add_cheese_input_1=982344
cooking_pizza_bake_input_0=982345
cooking_pizza_add_tomato_outcome_success=982346
cooking_pizza_add_cheese_outcome_success=982347
cooking_pizza_bake_outcome_success=982348
cooking_pizza_bake_outcome_fail=982349

cooking_pizza_add_meat=982350
cooking_pizza_add_meat_input_0=982351
cooking_pizza_add_meat_input_1=982352
cooking_pizza_add_meat_outcome_success=982353

cooking_pizza_add_anchovies=982354
cooking_pizza_add_anchovies_input_0=982355
cooking_pizza_add_anchovies_input_1=982356
cooking_pizza_add_anchovies_outcome_success=982357

cooking_pizza_add_pineapple=982358
cooking_pizza_add_pineapple_input_0=982359
cooking_pizza_add_pineapple_input_1=982360
cooking_pizza_add_pineapple_outcome_success=982361

# --- Stews ---
cooking_stew_add_potato=982362
cooking_stew_add_meat=982363
cooking_stew_cook=982364
cooking_stew_add_potato_input_0=982365
cooking_stew_add_potato_input_1=982366
cooking_stew_add_meat_input_0=982367
cooking_stew_add_meat_input_1=982368
cooking_stew_cook_input_0=982369
cooking_stew_add_potato_outcome_success=982370
cooking_stew_add_meat_outcome_success=982371
cooking_stew_cook_outcome_success=982372
cooking_stew_cook_outcome_fail=982373

cooking_curry_add_potato=982374
cooking_curry_add_meat=982375
cooking_curry_add_spice=982376
cooking_curry_cook=982377
cooking_curry_add_potato_input_0=982378
cooking_curry_add_potato_input_1=982379
cooking_curry_add_meat_input_0=982380
cooking_curry_add_meat_input_1=982381
cooking_curry_add_spice_input_0=982382
cooking_curry_add_spice_input_1=982383
cooking_curry_cook_input_0=982384
cooking_curry_add_potato_outcome_success=982385
cooking_curry_add_meat_outcome_success=982386
cooking_curry_add_spice_outcome_success=982387
cooking_curry_cook_outcome_success=982388
cooking_curry_cook_outcome_fail=982389

# --- Potatoes ---
cooking_baked_potato=982390
cooking_baked_potato_input_0=982391
cooking_baked_potato_outcome_success=982392
cooking_baked_potato_outcome_fail=982393

cooking_potato_add_butter=982394
cooking_potato_add_butter_input_0=982395
cooking_potato_add_butter_input_1=982396
cooking_potato_add_butter_outcome_success=982397

cooking_potato_add_cheese=982398
cooking_potato_add_cheese_input_0=982399
cooking_potato_add_cheese_input_1=982400
cooking_potato_add_cheese_outcome_success=982401

cooking_potato_add_egg=982402
cooking_potato_add_egg_input_0=982403
cooking_potato_add_egg_input_1=982404
cooking_potato_add_egg_outcome_success=982405
cooking_potato_add_egg_outcome_always_0=982406

cooking_potato_add_mushroom_onion=982407
cooking_potato_add_mushroom_onion_input_0=982408
cooking_potato_add_mushroom_onion_input_1=982409
cooking_potato_add_mushroom_onion_outcome_success=982410
cooking_potato_add_mushroom_onion_outcome_always_0=982411

cooking_potato_add_tuna_corn=982412
cooking_potato_add_tuna_corn_input_0=982413
cooking_potato_add_tuna_corn_input_1=982414
cooking_potato_add_tuna_corn_outcome_success=982415
cooking_potato_add_tuna_corn_outcome_always_0=982416

# --- Misc foods ---
cooking_sweetcorn=982417
cooking_sweetcorn_input_0=982418
cooking_sweetcorn_outcome_success=982419
cooking_sweetcorn_outcome_fail=982420

cooking_scrambled_egg_mix=982421
cooking_scrambled_egg_cook=982422
cooking_scrambled_egg_mix_input_0=982423
cooking_scrambled_egg_mix_input_1=982424
cooking_scrambled_egg_cook_input_0=982425
cooking_scrambled_egg_mix_outcome_success=982426
cooking_scrambled_egg_cook_outcome_success=982427
cooking_scrambled_egg_cook_outcome_fail=982428

cooking_fried_onions=982429
cooking_fried_onions_input_0=982430
cooking_fried_onions_outcome_success=982431
cooking_fried_onions_outcome_fail=982432

cooking_fried_mushrooms=982433
cooking_fried_mushrooms_input_0=982434
cooking_fried_mushrooms_outcome_success=982435
cooking_fried_mushrooms_outcome_fail=982436

cooking_mushroom_onion_combine=982437
cooking_mushroom_onion_combine_input_0=982438
cooking_mushroom_onion_combine_input_1=982439
cooking_mushroom_onion_combine_outcome_success=982440
cooking_mushroom_onion_combine_outcome_always_0=982441

cooking_tuna_corn_combine=982442
cooking_tuna_corn_combine_input_0=982443
cooking_tuna_corn_combine_input_1=982444
cooking_tuna_corn_combine_input_2=982445
cooking_tuna_corn_combine_outcome_success=982446

cooking_chocolate_cake=982447
cooking_chocolate_cake_input_0=982448
cooking_chocolate_cake_input_1=982449
cooking_chocolate_cake_outcome_success=982450

# --- Wine ---
cooking_wine=982451
cooking_wine_input_0=982452
cooking_wine_input_1=982453
cooking_wine_outcome_success=982454
cooking_wine_outcome_fail=982455

# --- Snails ---
cooking_thin_snail=982456
cooking_thin_snail_input_0=982457
cooking_thin_snail_outcome_success=982458
cooking_thin_snail_outcome_fail=982459

cooking_lean_snail=982460
cooking_lean_snail_input_0=982461
cooking_lean_snail_outcome_success=982462
cooking_lean_snail_outcome_fail=982463

cooking_fat_snail=982464
cooking_fat_snail_input_0=982465
cooking_fat_snail_outcome_success=982466
cooking_fat_snail_outcome_fail=982467

# --- Spit-Roast Rabbit ---
cooking_skewer_rabbit_meat=982468
cooking_skewer_rabbit_meat_input_0=982469
cooking_skewer_rabbit_meat_input_1=982470
cooking_skewer_rabbit_meat_outcome_success=982471

cooking_roast_rabbit_meat=982472
cooking_roast_rabbit_meat_input_0=982473
cooking_roast_rabbit_meat_outcome_success=982474
cooking_roast_rabbit_meat_outcome_fail=982475

# --- Hunter Meats (Pitfall Trapping) ---
cooking_larupia=982476
cooking_larupia_input_0=982477
cooking_larupia_outcome_success=982478
cooking_larupia_outcome_fail=982479

cooking_graahk=982480
cooking_graahk_input_0=982481
cooking_graahk_outcome_success=982482
cooking_graahk_outcome_fail=982483

cooking_kyatt=982484
cooking_kyatt_input_0=982485
cooking_kyatt_outcome_success=982486
cooking_kyatt_outcome_fail=982487

cooking_pyre_fox=982488
cooking_pyre_fox_input_0=982489
cooking_pyre_fox_outcome_success=982490
cooking_pyre_fox_outcome_fail=982491

cooking_sunlight_antelope=982492
cooking_sunlight_antelope_input_0=982493
cooking_sunlight_antelope_outcome_success=982494
cooking_sunlight_antelope_outcome_fail=982495

cooking_moonlight_antelope=982496
cooking_moonlight_antelope_input_0=982497
cooking_moonlight_antelope_outcome_success=982498
cooking_moonlight_antelope_outcome_fail=982499
