[gamevals.enums]
gameframe_dbrows=29997
toplevel_move_events=29998
[gamevals.tables]
gameframe=1214

[gamevals.dbrows]
gameframe_fullscreen=96710
gameframe_toplevel=96711
gameframe_osrs_stretch=96712
gameframe_pre_eoc=96713

